apiVersion: apps/v1
kind: Deployment
metadata:
  name: caps
  labels:
        app: caps
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: caps
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: caps
    spec:
      containers:
      - image: nasstoumi/caps
        imagePullPolicy: Always
        name: caps
        ports:
          - containerPort: 80
  



apiVersion: v1
kind: Service
metadata:
  name: caps
  labels:
    app: caps
spec:
  type: LoadBalancer
  selector:
    app: caps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80