apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap
  labels:
    app: cap
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: cap
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cap
    spec:
      containers:
      - image: nasstoumi/cap
        imagePullPolicy: Always
        name: cap
        ports:
          - containerPort: 80
  



apiVersion: v1
kind: Service
metadata:
  name: cap
  labels:
    app: cap
spec:
  type: LoadBalancer
  selector:
    app: cap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80