apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
        app: capstone
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - image: nasstoumi/capstone
        imagePullPolicy: Always
        name: capstone
        ports:
          - containerPort: 80
  



apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80