apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneudacity
  labels:
        app: capstoneudacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstoneudacity
  template:
    metadata:
      labels:
        app: capstoneudacity
    spec:
      containers:
      - name: capstoneudacity
        image: nasstoumi/capstoneudacity
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate



apiVersion: v1
kind: Service
metadata:
  name: capstoneudacity
  labels:
    app: capstoneudacity
spec:
  type: LoadBalancer
  selector:
    app: capstoneudacity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80